config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get '/about' =>'welcome#about'
  resources :projects
  devise_for :users
  resources :posts, :only => [ :new, :index, :create ]
  get "posts/:id", to: redirect("/%{id}")
  resources :posts, :path => "", :except => [ :new, :index ]
  resources :contacts, only: [:new, :create]

  root 'welcome#index'

  get '*path' => redirect('/')

end

app/models/contact.rb
class Contact < MailForm::Base

  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "My Contact Form",
      :to => "lunkaiwu@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize.to_s
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def prev
    Post.where(["id > ?", id ]).first
  end

  def next
    Post.where(["id < ?", id]).last
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize.to_s
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def prev
    Project.where(["id > ?", id ]).first
  end

  def next
    Project.where(["id < ?", id]).last
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render 'new'
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, :only => [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC').paginate(page: params[:page], per_page: 5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new', alert: "Unable to save the post"
    end
  end

  def show
    if request.path != post_path(@post)
      return redirect_to @post, status: :moved_permanently
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :slug)
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, :only => [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @projects = Project.all.order('created_at DESC')
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def find_project
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :link, :slug)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @posts = Post.all.limit(3).order("created_at DESC")
    @projects = Project.all.limit(3).order("created_at DESC")
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for :title, page_title.to_s
  end

  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    option = {
      autolink: true,
      on_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, option).render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">See ya！</h1>

<div class="skinny_wrapper wrapper_padding">
  <h1>Thank you for your message!</h1>
  <p>I will get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<% title "Contact" %>

<h1 id="page_title">See ya！</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= form_for @contact do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true %>

    <br>

    <%= f.label :email %><br>
    <%= f.text_field :email, required: true %>

    <br>

    <%= f.label :message %><br>
    <%= f.text_area :message, :as => :text %>

    <div class="hidden">
      <%= f.label :nickname %><br>
      <%= f.text_field :nickname, :hint => 'Leave this field blank' %>
    </div>

    <%= f.submit "Send Message", :class => "button" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <link href='//fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header id="main_navigation" class="clearfix">
    <%= link_to "Lun-Kai Wu", root_path, :class => "name" %>
    <nav>
      <%= link_to 'About', about_path %>
      <%= link_to 'Articles', posts_path %>
      <%= link_to 'Projects', projects_path %>
      <%= link_to 'Contact', new_contact_path %>
      <% if user_signed_in? %>
        <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
      <% end %>
    </nav>
  </header>

  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% elsif alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

<%= yield %>

  <footer id="main_footer">
    <p class="copyright">&copy; 2016 Lun-Kai Wu</p>
    <nav>
      <a href="https://github.com/lkwu" target="_blank" "><i class="fa fa-github-alt"></i></a>
      <a href="https://tw.linkedin.com/in/lunkaiew" target="_blank"><i class="fa fa-linkedin"></i></a>
      <a href="https://www.facebook.com/LunkaiWu" target="_blank"><i class="fa fa-facebook"></i></a>
    </nav>
  </footer>

</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
     var disqus_shortname = 'lunkaiwu';
     var disqus_identifier = '<%= @post.id %>';
     var disqus_title = '<%= @post.title %>';
     var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';

    /*
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');

        s.src = '//lunkaiwu.disqus.com/embed.js';

        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <h2><%= pluralize(@post.errors.count, "error") %> Prevented this post from saving.</h2>
    <ul>
      <% @post.error.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %><br>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :content, "Write your article here" %><br>
  <%= f.text_area :content %>

  <br>
  <br>

  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">Edit Post</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% title "Articles" %>

<h1 id="page_title">Stuff I've Written</h1>

<div id="post_wrapper" class="skinny_wrapper">
  <% @posts.each do |post| %>
    <div class="post">
      <p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
      <h2><%= link_to post.title, post %></h2>
      <hr>
    </div>
  <% end %>
</div>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1 id="page_title">New Post</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<% title @post.title %>

<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @post.created_at.strftime("%A, %B %d") %></p>
    <h1><%= @post.title %></h1>
    <hr>
  </header>

  <div id="content">
    <%= markdown(@post.content) %>
  </div>

  <% if user_signed_in? %>
    <div id="admin_links">
      <%= link_to 'Edit Article', edit_post_path(@post) %>
      <%= link_to 'Delete Article', post_path(@post), :method => :delete, data: {confirm: "Are you sure?"} %>
    </div>
  <% end %>

  <div id="post-order" class="clearfix">
    <div class="pre-post">
      <% if @post.prev %>
        <span>&laquo;</span> <%= link_to @post.prev.title, @post.prev %>
      <% end %>
    </div>

    <div class="next-post">
      <% if @post.next %>
        <%= link_to @post.next.title, @post.next %> <span>&raquo;</span>
      <% end %>
    </div>
  </div>


  <hr>

  <div id="share_box">
    <p>Share "<%= @post.title %>"</p>
    <a onclick="javascript:window.open('https://twitter.com/share?text=<%= @post.title %> by @lunkaiwu - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300'); void(0);">
      <i class="fa fa-twitter"></i>
    </a>
    <a onclick="javascript:window.open('https://www.facebook.com/share.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300'); void(0);">
      <i class="fa fa-facebook"></i>
    </a>
    <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300'); void(0);">
      <i class="fa fa-google-plus"></i>
    </a>
  </div>

  <hr>

  <%= render 'disqus' %>

</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <h2><%= pluralize(@project.errors.count, "error") %> Prevented this project from saving.</h2>
    <ul>
      <% @project.error.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %><br>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :description %><br>
  <%= f.text_area :description %>

  <br>
  <br>

  <%= f.label :link %><br>
  <%= f.text_field :link %>

  <br>
  <br>

  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">Edit Project</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<% title "Projects" %>

<h1 id="page_title">Stuff I've Built</h1>

<div id="post_wrapper" class="skinny_wrapper">
  <% @projects.each do |project| %>
    <div class="post">
      <p class="date"><%= project.created_at.strftime('%A, %B %d') %></p>
      <h2><%= link_to project.title, project %></h2>
      <hr>
    </div>
  <% end %>
</div>

app/views/projects/new.html.erb
<h1 id="page_title">New Post</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<% title @project.title %>

<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @project.created_at.strftime("%A, %B %d") %></p>
    <h1><%= @project.title %></h1>
    <hr>
  </header>

  <div id="content">
    <%= markdown(@project.description) %>

    <div class="button_wrapper">
      <a href="https://unbusymassage.herokuapp.com" class="project_button" target="_blank">Visit <%= @project.title %></a>
    </div>
  </div>

  <% if user_signed_in? %>
    <div id="admin_links">
      <%= link_to 'Edit', edit_project_path(@project) %>
      <%= link_to 'Delete', project_path(@project), :method => :delete, data: {confirm: "Are you sure?"} %>
    </div>
  <% end %>



  <hr>
</div>

app/views/welcome/about.html.erb
<% title "About" %>

<h1 id="page_title">About</h1>

<div id="post_wrapper" class="skinny_wrapper">
    <div class="post about">
      <p>喜歡旅行，喜愛程式語言。對於自己動手做網站一直懷抱熱衷，覺得這是一件很酷的事情，所以很衝動地放下工作，跑去參加了一個短期進修，學習Rails，以及新創產業等相關的知識。</p>
      <p>關於程式設計、建構網站...等知識實在太多、更新太快了，但卻熱此不疲地看書、上網找資料、也跟同學討論，再試著把新功能做出來，我覺得這是一件很快樂的事。</p>
      <p>這個Blog目前僅有非常簡單基本的功能，分享的內容也沒有太高的技術含量 XD，網路上有很多專研很深很久的高手，跟他們比起來我只是個菜鳥，所以也不敢班門弄斧，只是將我學到的新技能寫到這裡，這也是督促自己不斷學習的方式。 :)</p>
      <p><a href="https://unbusymassage.herokuapp.com">不忙按摩</a>是我曾經參與的專案，負責前端網頁、智付寶第三方支付建立、後端部署。當時因為開發時間不多，所以前端網頁只考慮電腦上瀏覽，RWD是在專案結束之後，自己再加上去的。</p>
      <p>程式設計一定會不斷地更新，未來我希望退休之後，可以開家民宿然後一邊繼續寫程式 XD</p>
    </div>
</div>

app/views/welcome/index.html.erb
<div class="wraper wrapper_padding">
  <div class="homepage_content">
    <h2>Articles</h2>
    <hr>
    <% @posts.each do |post| %>
      <h3><%= link_to post.title, post %></h3>
      <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
    <% end %>
  </div>
</div>